config/routes.rb
AmandaFrontend::Application.routes.draw do
  get "browse/configs"

  get "browse/dle"

  get "browse/tape"

  get "browse/run"

  resources :amanda_configs
  resources :dles
  resources :runs
  resources :tapes

end

app/models/amanda_config.rb
class AmandaConfig < ActiveRecord::Base
    has_many :tapes
    has_many :runs
    has_many :dles

    def to_s
        "#{self.name}"
    end
end

app/controllers/amanda_configs_controller.rb
class AmandaConfigsController < ApplicationController
  # GET /amanda_configs
  # GET /amanda_configs.xml
  def index
    @amanda_configs = AmandaConfig.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @amanda_configs }
    end
  end

  # GET /amanda_configs/1
  # GET /amanda_configs/1.xml
  def show
    @amanda_config = AmandaConfig.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @amanda_config }
    end
  end

  # GET /amanda_configs/new
  # GET /amanda_configs/new.xml
  def new
    @amanda_config = AmandaConfig.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @amanda_config }
    end
  end

  # GET /amanda_configs/1/edit
  def edit
    @amanda_config = AmandaConfig.find(params[:id])
  end

  # POST /amanda_configs
  # POST /amanda_configs.xml
  def create
    @amanda_config = AmandaConfig.new(params[:amanda_config])

    respond_to do |format|
      if @amanda_config.save
        format.html { redirect_to(@amanda_config, :notice => 'Amanda config was successfully created.') }
        format.xml  { render :xml => @amanda_config, :status => :created, :location => @amanda_config }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @amanda_config.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /amanda_configs/1
  # PUT /amanda_configs/1.xml
  def update
    @amanda_config = AmandaConfig.find(params[:id])

    respond_to do |format|
      if @amanda_config.update_attributes(params[:amanda_config])
        format.html { redirect_to(@amanda_config, :notice => 'Amanda config was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @amanda_config.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /amanda_configs/1
  # DELETE /amanda_configs/1.xml
  def destroy
    @amanda_config = AmandaConfig.find(params[:id])
    @amanda_config.destroy

    respond_to do |format|
      format.html { redirect_to(amanda_configs_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/amanda_configs/_form.html.erb
<%= form_for(@amanda_config) do |f| %>
  <% if @amanda_config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@amanda_config.errors.count, "error") %> prohibited this amanda_config from being saved:</h2>

      <ul>
      <% @amanda_config.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/amanda_configs/edit.html.erb
<h1>Editing amanda_config</h1>

<%= render 'form' %>

<%= link_to 'Show', @amanda_config %> |
<%= link_to 'Back', amanda_configs_path %>

app/views/amanda_configs/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>DLEs</th>
    <th>Runs</th>
  </tr>

<% @amanda_configs.each do |amanda_config| %>
  <tr>
    <td><%= link_to amanda_config.name, amanda_config %></td>
    <td>
        <% amanda_config.dles.order(:host, :disk).each do |dle| %>
          <%= link_to dle.name, dle %><br />
        <% end %>
      </td>
      <td>
        <% amanda_config.runs.order("date DESC").limit(10).each do |run| %>
          <%= link_to run.pretty_date, run %><br />
        <% end %>
      </td>
  </tr>
<% end %>
</table>

app/views/amanda_configs/new.html.erb
<h1>New amanda_config</h1>

<%= render 'form' %>

<%= link_to 'Back', amanda_configs_path %>

app/views/amanda_configs/show.html.erb
<h3><%= link_to "Config", :amanda_configs %>: <%= @amanda_config.name %></h3>

<table>
    <tr>
        <th colspan=4>DLEs</th>
    </tr>
    <tr>
        <th>Host</th>
        <th>Disk</th>
        <th>Last run</th>
        <th>Last level0</th>
    </tr>
    <% @amanda_config.dles.each do |dle| %>
      <tr>
        <td><%= dle.host %></td>
        <td><%= link_to dle.disk, dle %></td>
        <td><%= dle.last_run.run.pretty_date %></td>
        <td><%= dle.last_lev0.run.pretty_date %></td>
      </tr>
    <% end %>
</table>


        <% @amanda_config.runs.order("date DESC").limit(10).each do |run| %>
            <%= link_to run.pretty_date, run %><br />
        <% end %>
    </td>