config/routes.rb
AmandaFrontend::Application.routes.draw do
  get "browse/configs"

  get "browse/dle"

  get "browse/tape"

  get "browse/run"

  resources :amanda_configs
  resources :dles
  resources :runs
  resources :tapes

end

app/models/dle.rb
class Dle < ActiveRecord::Base
  belongs_to :amanda_config
  has_many :dle_runs

  def to_s
    "#{self.amanda_config}:#{self.host}/#{self.disk}"
  end

  def last_run
    self.dle_runs.sort_by {|dr| dr.run.date}.last
  end

  def last_lev0
    self.dle_runs.where(:level => 0).sort_by {|dr| dr.run.date}.last
  end

  def name
    "#{self.host}/#{self.disk}"
  end
end

app/controllers/dles_controller.rb
class DlesController < ApplicationController
  # GET /dles
  # GET /dles.xml
  def index
    @dles = Dle.find(:all, :order => [:amanda_config_id, :host, :disk])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dles }
    end
  end

  # GET /dles/1
  # GET /dles/1.xml
  def show
    @dle = Dle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dle }
    end
  end

  # GET /dles/new
  # GET /dles/new.xml
  def new
    @dle = Dle.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dle }
    end
  end

  # GET /dles/1/edit
  def edit
    @dle = Dle.find(params[:id])
  end

  # POST /dles
  # POST /dles.xml
  def create
    @dle = Dle.new(params[:dle])

    respond_to do |format|
      if @dle.save
        format.html { redirect_to(@dle, :notice => 'Dle was successfully created.') }
        format.xml  { render :xml => @dle, :status => :created, :location => @dle }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dles/1
  # PUT /dles/1.xml
  def update
    @dle = Dle.find(params[:id])

    respond_to do |format|
      if @dle.update_attributes(params[:dle])
        format.html { redirect_to(@dle, :notice => 'Dle was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dles/1
  # DELETE /dles/1.xml
  def destroy
    @dle = Dle.find(params[:id])
    @dle.destroy

    respond_to do |format|
      format.html { redirect_to(dles_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/dles/_form.html.erb
<%= form_for(@dle) do |f| %>
  <% if @dle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dle.errors.count, "error") %> prohibited this dle from being saved:</h2>

      <ul>
      <% @dle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dles/edit.html.erb
<h1>Editing dle</h1>

<%= render 'form' %>

<%= link_to 'Show', @dle %> |
<%= link_to 'Back', dles_path %>

app/views/dles/index.html.erb
<h1>Listing dles</h1>

<table>
  <tr>
    <th>Config</th>
    <th>Host</th>
    <th>Disk</th>
    <th>Last run</th>
    <th>Last level0</th>
  </tr>

<% @dles.each do |dle| %>
  <tr>
    <td><%= link_to dle.amanda_config.name, dle.amanda_config %></td>
    <td><%= dle.host %></td>
    <td><%= link_to dle.disk, dle %></td>
    <td><%= dle.last_run.run.date.strftime("%Y-%m-%d %H:%M") %></td>
    <td><%= dle.last_lev0.run.date.strftime("%Y-%m-%d %H:%M") %></td>
  </tr>
<% end %>
</table>

app/views/dles/new.html.erb
<h1>New dle</h1>

<%= render 'form' %>

<%= link_to 'Back', dles_path %>

app/views/dles/show.html.erb
<p id="notice"><%= notice %></p>

<h3>DLE: <%= link_to @dle.amanda_config.name, @dle.amanda_config %><%= ":#{@dle.host}/#{@dle.disk}" %></h3>

<table>
    <tr><th colspan=4>Runs</th></tr>
    <tr>
        <th>Date</th>
        <th>Level</th>
        <th>Size</th>
        <th>Tapes</th>
    </tr>
    <% @dle.dle_runs.each do |dle_run| %>
        <tr>
            <td><%= link_to dle_run.run.date.strftime("%Y-%m-%d %H:%M"), dle_run.run %></td>
            <td><%= dle_run.level %></td>
            <td><%= dle_run.size_human %></td>
            <td>
                <% dle_run.dle_run_tapes.each do |drt| %>
                    <%= link_to drt.tape.name, drt.tape %><br />
                <% end %>
            </td>
        </tr>
    <% end %>
</table>