config/routes.rb
AmandaFrontend::Application.routes.draw do
  get "browse/configs"

  get "browse/dle"

  get "browse/tape"

  get "browse/run"

  resources :amanda_configs
  resources :dles
  resources :runs
  resources :tapes

end

app/models/tape.rb
class Tape < ActiveRecord::Base
  belongs_to :amanda_config
  has_many :dle_run_tapes

  def to_s
    "#{self.amanda_config}:#{self.name}"
  end

  def most_recent_run
    self.dle_run_tapes.joins(:run).order("runs.date ASC").first.run
  end
end

app/controllers/tapes_controller.rb
class TapesController < ApplicationController
  # GET /tapes
  # GET /tapes.xml
  def index
    @tapes = Tape.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tapes }
    end
  end

  # GET /tapes/1
  # GET /tapes/1.xml
  def show
    @tape = Tape.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tape }
    end
  end

  # GET /tapes/new
  # GET /tapes/new.xml
  def new
    @tape = Tape.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tape }
    end
  end

  # GET /tapes/1/edit
  def edit
    @tape = Tape.find(params[:id])
  end

  # POST /tapes
  # POST /tapes.xml
  def create
    @tape = Tape.new(params[:tape])

    respond_to do |format|
      if @tape.save
        format.html { redirect_to(@tape, :notice => 'Tape was successfully created.') }
        format.xml  { render :xml => @tape, :status => :created, :location => @tape }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tape.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tapes/1
  # PUT /tapes/1.xml
  def update
    @tape = Tape.find(params[:id])

    respond_to do |format|
      if @tape.update_attributes(params[:tape])
        format.html { redirect_to(@tape, :notice => 'Tape was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tape.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tapes/1
  # DELETE /tapes/1.xml
  def destroy
    @tape = Tape.find(params[:id])
    @tape.destroy

    respond_to do |format|
      format.html { redirect_to(tapes_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/tapes/_form.html.erb
<%= form_for(@tape) do |f| %>
  <% if @tape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tape.errors.count, "error") %> prohibited this tape from being saved:</h2>

      <ul>
      <% @tape.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tapes/edit.html.erb
<h1>Editing tape</h1>

<%= render 'form' %>

<%= link_to 'Show', @tape %> |
<%= link_to 'Back', tapes_path %>

app/views/tapes/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Last used</th>
    <th>Contents</th>
  </tr>

<% @tapes.each do |tape| %>
  <tr>
    <td><%= link_to tape.name, tape %></td>
    <td><%= link_to tape.most_recent_run.pretty_date, tape.most_recent_run %></td>
    <td>
      <table>
        <% DleRunTape.where(:tape_id => tape.id).joins(:dle_run).where("dle_runs.run_id = ?", tape.most_recent_run.id).joins(:dle).order("host", "disk").each do |drt| %>
          <tr>
            <td><%= link_to drt.dle.name, drt.dle %></td>
            <td><%= drt.dle_run.level %></td>
            <td><%= drt.size_human %></td>
          </tr>
        <% end %>
      </table>
    </td>
  </tr>
<% end %>
</table>

app/views/tapes/new.html.erb
<h1>New tape</h1>

<%= render 'form' %>

<%= link_to 'Back', tapes_path %>

app/views/tapes/show.html.erb
<h3><%= link_to "Tape", :tapes %>: <%= link_to @tape.amanda_config.name, @tape.amanda_config %>:<%= @tape.name %></h3>
<table>
    <tr><th colspan=4>Runs</th></tr>
    <tr>
        <th>Date</th>
        <th>DLE</th>
        <th>Level</th>
        <th>Size</th>
        <th>Overwritten by</th>
    </tr>
    <% DleRunTape.where(:tape_id => @tape.id).joins(:run).joins(:dle).order("runs.date DESC", "dles.host", "dles.disk").each do |drt| %>
        <tr>
            <td><%= link_to drt.run.date.strftime("%Y-%m-%d %H:%M"), drt.run %></td>
            <td><%= link_to "#{drt.dle.host}/#{drt.dle.disk}", drt.dle %></td>
            <td><%= drt.dle_run.level %></td>
            <td><%= drt.size_human %></td>
            <td>
                <% if drt.overwritten_by_run_id %>
                    <%= link_to Run.find(drt.overwritten_by_run_id).date.strftime("%Y-%m-%d %H:%M"), Run.find(drt.overwritten_by_run_id) %>
                <% end %>
            </td>
        </tr>
    <% end %>
</table>