config/routes.rb
AmandaFrontend::Application.routes.draw do
  get "browse/configs"

  get "browse/dle"

  get "browse/tape"

  get "browse/run"

  resources :amanda_configs
  resources :dles
  resources :runs
  resources :tapes

end

app/models/run.rb
class Run < ActiveRecord::Base
  belongs_to :amanda_config
  has_many :dle_runs
  has_many :overwritten_dle_run_tapes, :class_name => :dle_run_tapes

  def to_s
    "#{self.amanda_config}:#{self.date}"
  end

  def pretty_date
    self.date.strftime("%Y-%m-%d %H:%M")
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  # GET /runs
  # GET /runs.xml
  def index
    @runs = Run.order("date DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @runs }
    end
  end

  # GET /runs/1
  # GET /runs/1.xml
  def show
    @run = Run.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @run }
    end
  end

  # GET /runs/new
  # GET /runs/new.xml
  def new
    @run = Run.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @run }
    end
  end

  # GET /runs/1/edit
  def edit
    @run = Run.find(params[:id])
  end

  # POST /runs
  # POST /runs.xml
  def create
    @run = Run.new(params[:run])

    respond_to do |format|
      if @run.save
        format.html { redirect_to(@run, :notice => 'Run was successfully created.') }
        format.xml  { render :xml => @run, :status => :created, :location => @run }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @run.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /runs/1
  # PUT /runs/1.xml
  def update
    @run = Run.find(params[:id])

    respond_to do |format|
      if @run.update_attributes(params[:run])
        format.html { redirect_to(@run, :notice => 'Run was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @run.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.xml
  def destroy
    @run = Run.find(params[:id])
    @run.destroy

    respond_to do |format|
      format.html { redirect_to(runs_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/runs/_form.html.erb
<%= form_for(@run) do |f| %>
  <% if @run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@run.errors.count, "error") %> prohibited this run from being saved:</h2>

      <ul>
      <% @run.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/runs/edit.html.erb
<h1>Editing run</h1>

<%= render 'form' %>

<%= link_to 'Show', @run %> |
<%= link_to 'Back', runs_path %>

app/views/runs/index.html.erb
<table>
  <tr>
    <th>Date</th>
    <th>Contents</th>
  </tr>

<% @runs.each do |run| %>
  <tr>
    <td><%= link_to run.pretty_date, run %></td>
    <td><table>
      <% run.dle_runs.each do |dr| %>
        <tr>
          <td><%= link_to dr.dle.name, dr.dle %></td> 
          <td><%= dr.level %></td>
          <td><%= dr.size_human %></td>
        </tr>
      <% end %>
    </table></td>
  </tr>
<% end %>
</table>

app/views/runs/new.html.erb
<h1>New run</h1>

<%= render 'form' %>

<%= link_to 'Back', runs_path %>

app/views/runs/show.html.erb
<h3> <%= link_to @run.amanda_config.name, @run.amanda_config %> <%= link_to "Run", :runs %> @ <%= @run.pretty_date %></h3>

<table>
    <tr>
        <th>DLE</th>
        <th>Level</th>
        <th>Size</th>
        <th>Tapes</th>
    </tr>
  <% @run.dle_runs.each do |dr| %>
    <tr>
      <td><%= link_to dr.dle.name, dr.dle %></td> 
      <td><%= dr.level %></td>
      <td><%= dr.size_human %></td>
      <td>
        <table>
            <% dr.dle_run_tapes.each do |drt| %>
                <tr>
                    <td><%= link_to drt.tape.name, drt.tape %></td>
                    <td><%= drt.size_human %></td>
                </tr>
            <% end %>
        </table>
    </td>

    </tr>
  <% end %>
</table>